name:                mockit
version:             0.1.0.0
github:              "jpittis/mockit"
license:             BSD3
author:              "Jake Pittis"
maintainer:          "jakepittis@gmail.com"
copyright:           "2017 Jake Pittis"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: A simple but effective failure testing proxy.

description: Please see the README on Github at <https://github.com/jpittis/mockit#readme>

dependencies:
- base >= 4.7 && < 5
- network
- bytestring
- async
- aeson
- text
- scotty
- mtl
- transformers
- containers
- req
- data-default-class
- optparse-generic

library:
  source-dirs: src

executables:
  mockit-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mockit
  mockit-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mockit

tests:
  mockit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mockit
    - hspec
